// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYIyTO1I1k7zuqd86IZ_V3DQbq3w4cVM',
    appId: '1:480603613424:web:8b5d8cff8c72b3b1333a35',
    messagingSenderId: '480603613424',
    projectId: 'hr-ms-95de9',
    authDomain: 'hr-ms-95de9.firebaseapp.com',
    storageBucket: 'hr-ms-95de9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnDQyyVl-E5Ty_Zm1zhSaOsVHrzLnyoY',
    appId: '1:480603613424:ios:60f4d2c2830060c0333a35',
    messagingSenderId: '480603613424',
    projectId: 'hr-ms-95de9',
    storageBucket: 'hr-ms-95de9.firebasestorage.app',
    iosBundleId: 'com.example.hrMs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDYIyTO1I1k7zuqd86IZ_V3DQbq3w4cVM',
    appId: '1:480603613424:web:47d39167adc40645333a35',
    messagingSenderId: '480603613424',
    projectId: 'hr-ms-95de9',
    authDomain: 'hr-ms-95de9.firebaseapp.com',
    storageBucket: 'hr-ms-95de9.firebasestorage.app',
  );
}
